# acquisition/Dockerfile
FROM python:3.12-slim

WORKDIR /app

# Copier le script fetch_tle.py depuis le dossier acquisition
COPY fetch_tle.py .

# Installer les dépendances Python
RUN pip install psycopg2-binary requests

# Commande par défaut
CMD ["python", "fetch_tle.py"]
